//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.EMIS.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.EMIS.Common.Resource.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên đã tồn tại trong hệ thống.
        /// </summary>
        public static string Error_DuplicateTeacherCode {
            get {
                return ResourceManager.GetString("Error_DuplicateTeacherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được phép để trống..
        /// </summary>
        public static string Error_EmptyFullName {
            get {
                return ResourceManager.GetString("Error_EmptyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên không được phép để trống..
        /// </summary>
        public static string Error_EmptyTeacherCode {
            get {
                return ResourceManager.GetString("Error_EmptyTeacherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng..
        /// </summary>
        public static string Error_NotEmail {
            get {
                return ResourceManager.GetString("Error_NotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được hỗ trợ..
        /// </summary>
        public static string Error_UserMsg {
            get {
                return ResourceManager.GetString("Error_UserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Table_A3 {
            get {
                return ResourceManager.GetString("Table_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu cán bộ.
        /// </summary>
        public static string Table_B3 {
            get {
                return ResourceManager.GetString("Table_B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Table_C3 {
            get {
                return ResourceManager.GetString("Table_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Table_D3 {
            get {
                return ResourceManager.GetString("Table_D3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chuyên môn.
        /// </summary>
        public static string Table_E3 {
            get {
                return ResourceManager.GetString("Table_E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thiết bị môn.
        /// </summary>
        public static string Table_F3 {
            get {
                return ResourceManager.GetString("Table_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý kho-phòng.
        /// </summary>
        public static string Table_G3 {
            get {
                return ResourceManager.GetString("Table_G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo QLTB.
        /// </summary>
        public static string Table_H3 {
            get {
                return ResourceManager.GetString("Table_H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string Table_I3 {
            get {
                return ResourceManager.GetString("Table_I3", resourceCulture);
            }
        }
    }
}
